version: '3.7'
services:
  scrumbot:
    image: docker.okidoo.co/node-dev-16:latest
    container_name: scrumbot
    dns: 1.1.1.1
    volumes:
      - ./.npmrc:/home/node/.npmrc
      - ../:/home/node/app
      - ~/.ssh/:/home/node/.ssh/
    networks:
      - scrumbot
    command: tail -F anything
    env_file:
      - ./.env

networks:
  scrumbot: